#!/bin/sh
overlook()
{
    ls -al
}
 
cdfunction()
{
    echo "the dir is $1"  
    cd $1;echo "pwd is `pwd`"
}
#main()
clear
echo "welcome !"
echo "####################################"
echo "minitools"
echo "####################################"
echo "f -> find , l -> ls , e -> exit ,c -> cd "
# test list for
for var in  a b c  
do
    echo "############### $var ###################"
done
#
# test  for
# the name of var is nothing ,it depend on $#
for bb  
do
    echo "##################################"
done
# need sudo dpkg-reconfigure dash; ubuntu use the dash 
for((i=1;i<10;i++)) 
do
    echo "************************************"
done

# test the select in 
select var2 in aa bb cc
do
    echo "$var2"
    break
done

#test until 
n=0
until [ $n -eq 3 ] 
do
# 如果是用的数字变量的话要要通过let，然后就是要用“”来屏蔽+的原来的作用。
    let "n=n+1" 
    echo "**************"
done   

while true
do
echo "input a char"
read MAINCMD
# test the input
if [ $MAINCMD = f -o $MAINCMD = l -o $MAINCMD = e -o $MAINCMD = m ]
then
    echo "the MAINCMD is ok "
else
    echo "the MAINCMD is err ,you put $MAINCMD "
fi
case $MAINCMD in
F|f)
    overlook;;
l|L)
    overlook;;
e|E)
    exit 0;;
m|M)
   echo "put a name "
   read fname
   `touch $fname`
   echo "make success";;
c|C)
    echo "input a dir"
    read DIR
    cdfunction $DIR;;
*)
    echo "eorr maincmd '$MAINCMD'";;
esac
done
