#!/bin/sh
overlook()
{
    ls -al
}
 
cdfunction()
{
    echo "the dir is $1"  
    cd $1;echo "pwd is `pwd`"
}
#main()
clear
echo "welcome !"
echo "####################################"
echo "minitools"
echo "####################################"
echo "f -> find , l -> ls , e -> exit ,c -> cd "
  


while true
do
echo "input a char"
read MAINCMD
# test the input
case $MAINCMD in
F|f)
    overlook;;
l|L)
    overlook;;
e|E)
    exit 0;;
c)
    echo "input a dir"
    read DIR
    cdfunction $DIR;;
*)
    echo "eorr maincmd '$MAINCMD'";;
esac
done
