#!/bin/sh
overlook()
{
    ls -al
}
 
cdfunction()
{
    echo "the dir is $1"  
    cd $1;echo "pwd is `pwd`"
    overlook
}
#main()
echo "welcome !"
echo "####################################"
echo "minitools"
echo "####################################"
  


while true
do
read MAINCMD
# test the input
if [ MAINCMD != [f,l,e,F,L,E,c] ]
then
    echo err input
fi
case $MAINCMD in
F|f)
    overlook;;
l|L)
    overlook;;
e|E)
    exit 0;;
c)
    read DIR
    cdfunction $DIR;;
*)
    echo "eorr maincmd '$MAINCMD'";;
esac
done
